# Continuous Integration Pipeline

name: 'ci'
on:
  pull_request:
    branches:
      - master

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Format Check
        run: npx gulp format-check

#  lint_check:        
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '19.x'
#      - name: Install Dependencies
#        run: npm ci
#      - name: Run Lint Check
#        run: npm run lint
  
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npx gulp mocha

  test_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Webpack
        run: npx gulp webpack

  rebuild_libnode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y gobject-introspection gtk-doc-tools libtool libgirepository1.0-dev autoconf automake libgladeui-dev libgirepository1.0-dev build-essential libgtk-3-dev gir1.2-gtk-3.0
      - run: python3 gimp/pictonode-gimp-plugin/GIMP\ 2.99/scripts/GtkNodes/test_setup.py

