# Continuous Integration Pipeline

name: 'ci'
on:
  pull_request:
    branches:
      - master

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Install autopep8
        run: python -m pip install autopep8
      - name: Run Format Check
        run: bash ./scripts/format_check.sh 

#  lint_check:        
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '19.x'
#      - name: Install Dependencies
#        run: npm ci
#      - name: Run Lint Check
#        run: npm run lint
  
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run JS Unit Tests
        run: bash ./scripts/mocha_test.sh

  integration_test:
    runs-on: ubuntu-latest
    services:
          postgres:
            image: postgres
            env:
              POSTGRES_USER: ontario_test
              POSTGRES_PASSWORD: ontario_test
              POSTGRES_DB: ontario_test
            ports:
              - 5432:5432
            # Set health checks to wait until postgres has started
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Install pytest
        run: python -m pip install pytest
      - name: Install GEGL
        run: sudo apt update -y && sudo apt install -y libgegl-dev
      - name: Install requirements
        run: |
          pushd ./backend/ontario-web
          python -m pip install -r requirements.txt
      - name: Run Pytest
        run: xvfb-run bash ./scripts/pytest_test.sh

  test_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Webpack
        run: bash ./scripts/test_webpack.sh

  rebuild_libnode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update -y && sudo apt install -y gobject-introspection gtk-doc-tools libtool libgirepository1.0-dev autoconf automake libgladeui-dev libgirepository1.0-dev build-essential libgtk-3-dev gir1.2-gtk-3.0
      - run: python3 gimp/pictonode-gimp-plugin/GIMP\ 2.99/scripts/GtkNodes/test_setup.py
